# Generated by Django 6.0.7 on 2026-07-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('cta_text', models.CharField(default='Shop Now', max_length=100)),
                ('cta_link', models.CharField(default='#', max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('couples', 'Couples'), ('smart', 'Smart Watches')], default='men', max_length=20)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_flash_sale', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image2_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
