# Generated by Django 6.0.7 on 2026-08-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sitesettings_flash_sale_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smartphones', 'Smartphones'), ('accessories', 'Accessories'), ('smart-watches', 'Smart Watches'), ('audio-gadgets', 'Audio & Gadgets')], default='smartphones', max_length=20),
        ),
    ]
