# Generated by Django 6.0.7 on 2026-08-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
