# Generated by Django 6.0.7 on 2026-08-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_banner_image_url_alter_product_image2_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_phone',
            field=models.CharField(blank=True, default='03407608138', max_length=50, null=True),
        ),
    ]
