services:
  - type: web
    name: madina-mobiles
    env: python
    buildCommand: "./build.sh"
    startCommand: "/opt/render/project/src/.venv/bin/gunicorn sveston_watches.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
